version: "3"

services:
  database:
    image: postgres:15
    container_name: database
    environment:
      - POSTGRES_DB=qwe
      - POSTGRES_USER=qwe
      - POSTGRES_PASSWORD=qwe
    expose:
      - "5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: bash -c "/app/start-django-dev.sh"
    container_name: django
    restart: unless-stopped
    volumes:
      - "./src:/app/src"
    links:
      - database
    depends_on:
      - database
    environment:
      - DEBUG
volumes:
  db_data: